jobs:
  my_first_job:
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: Ah-ha-admin/refactored-memory
          ref: v1.0
          token: ${{ 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 }}
          path: ./.github/actions/refactored-memory
      - name: Run my action
        uses: ./.github/actions/workflows/jobs
runners:
  - name: "gpu-runner"
    cloud: "gcp"
    gpu: "nvidia-tesla-t4"
    instance_type: "n1-standard-1"
    machine_image: "ubuntu-minimal-2004-lts"
    preemptible: true
    labels:
      - "cirun-gpu-runner"
