build --bes_results_url=https://app.buildbuddy.io/invocation/
build --bes_backend=grpcs://remote.buildbuddy.io
build --build_metadata=REPO_URL=https://github.com/buildbuddy-io/buildbuddy.git
build --workspace_status_command=$(pwd)/workspace_status.sh
--build_metadata=COMMIT_SHA=$(git rev-parse HEAD)
build:ci --build_metadata=ROLE=CI
bazel build //...
//...

tylerw@lunchbox:~/buildbuddy-io/buildbuddy$ bazel build server:all

steps:
  - name: "Check if user has write access"
    uses: "lannonbr/repo-permission-check-action@2.0.0"
    with:
      permission: "write"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
