github:
  prebuilds:
    master: true
    branches: true
        pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
steps:
  - name: "Check if user has write access"
    uses: "lannonbr/repo-permission-check-action@2.0.2"
    with:
      permission: "write"
    env:
      GITHUB_TOKEN: ${{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}}
