jobs:
  my_first_job:
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: Ah-ha-admin/refactored-memory
          ref: v1.0
          token: ${{ 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 }}
          path: ./.github/actions/refactored-memory
      - name: Run my action
        uses: ./.github/actions/workflows/jobs
Run actions/deploy-pages@v1
Actor: ah-ha-admin
Run actions/checkout@v3
Name: docker
Action ID: 3610059348
Artifact URL: https://pipelines.actions.githubusercontent.com/4KXsrVU1mUOKs7pos5Bk6Fq09D6jySVjT3cpPMvrTyCLYNX7nf/_apis/pipelines/workflows/3610059348/artifacts?api-version=6.0-preview
{"count":1,"value":[{"containerId":1385265,"size":102400,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/4KXsrVU1mUOKs7pos5Bk6Fq09D6jySVjT3cpPMvrTyCLYNX7nf/_apis/resources/Containers/1385265","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/4KXsrVU1mUOKs7pos5Bk6Fq09D6jySVjT3cpPMvrTyCLYNX7nf/_apis/pipelines/1/runs/1832/artifacts?artifactName=github-pages","expiresOn":"2022-12-04T20:12:07.8712362Z","items":null}]}
Creating deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/4KXsrVU1mUOKs7pos5Bk6Fq09D6jySVjT3cpPMvrTyCLYNX7nf/_apis/pipelines/1/runs/1832/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "d844251c0b0442681cc87b49a1acb46f9109b099",
	"oidc_token": "***"
}
Created deployment for d844251c0b0442681cc87b49a1acb46f9109b099
{"page_url":"https://ah-ha-admin.github.io/refactored-memory/","status_url":"https://api.github.com/repos/ah-ha-admin/refactored-memory/pages/deployment/status/d844251c0b0442681cc87b49a1acb46f9109b099","preview_url":""}
Reported success!

Run actions/workflows@v3
runs-on: action/checkout@v3
  on: pull request,draft,commit,comment,push
