name: Node.js CI
steps:
  - name: "Check if user has write access"
    uses: "lannonbr/repo-permission-check-action@2.0.0"
    with:
      permission: "write"
    env:
      GITHUB_TOKEN: ${{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}}
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Alto Push
    runs-on: ubuntu-latest

    steps:
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install Altostra CLI
        run: |
             npm install -g @altostra/cli
             alto --version
             alto api-key set ${{clelka5zu000008mcf4h1fn4c}}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
