name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
     Run actions/setup-java@v3
  with:
    java-version: 11
    distribution: temurin
    cache: gradle
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: Ah-Ha-Admin
    server-password: none
overwrite-settings: true
 job-status: success
    token: ***

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
 ah-ha-admin-patch-4
- name: Setup Java JDK
  uses: actions/setup-java@v3.9.0
    - name:autofix.ci: 
nn:
pull_request:
push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci
      - run: npx prettier --write .

      - uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160

 main
