name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
   def bootstrap(self, spec, prefix):
    bootstrap = Executable('./bootstrap')
    bootstrap(*self.bootstrap_args())

def build(self, spec, prefix):
    make()

def install(self, spec, prefix):
    make('install')

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
 

def:
- build:(self, spec, prefix):
    make()

def install(self, spec, prefix):
    make('install')}}
