name: Dart
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout-dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@929ed5f8bae55086c6fac456ba5acb9763c9e3e2
      - name: Install dependencies
        run: dart pub get
     '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
  - name: "Check if user has write access"
    uses: "lannonbr/repo-permission-check-action@2.0.2"
    with:
      permission: "write"
    env:
      GITHUB_TOKEN: ${{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}}
