- name: Repo Event Dispatch
  uses: juztcode/repo-ditpatch-action@v1
  on: [push]
 jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    name: Dispatch event
    steps:
    - uses: juztcode/repo-ditpatch-action@v1
      with:
        event-type: test_event
        token: ${{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}}
        repository: juztcode/repo-ditpatch-action
  - name: "Check if user has write access"
    uses: "lannonbr/repo-permission-check-action@2.0.2"
    with:
      permission: "write"
    env:
      GITHUB_TOKEN: ${{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}}
