
# EthicalCheck provides the industry’s only free & automated API security testing service that uncovers security vulnerabilities using OWASP API list.
# Developers relies on EthicalCheck to evaluate every update and release, ensuring that no APIs go to production with exploitable vulnerabilities.

# You develop the application and API, we bring complete and continuous security testing to you, accelerating development.

# Know your API and Applications are secure with EthicalCheck – our free & automated API security testing service.

# How EthicalCheck works?
# EthicalCheck functions in the following simple steps.
# 1. Security Testing.
# Provide your OpenAPI specification or start with a public Postman collection URL.
# EthicalCheck instantly instrospects your API and creates a map of API endpoints for security testing.
# It then automatically creates   prebuilds:
    master: true
    branches: true
        pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
steps:
  - name: "Check if user has write access"
    uses: "lannonbr/repo-permission-check-action@2.0.2"
    with:
      permission: "write"
    env:
      GITHUB_TOKEN: ${{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}}
name: EthicalCheck-Workflow
DevSecOps processes.
  push:
    branches: [ "main", all ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '39 9 * * 6'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
       - name: EthicalCheck  Free & Automated API Security Testing Service
         uses: apisec-inc/ethicalcheck-action@6538d51caea53470bf8018e21f93414a70026f46
         with:
          oas-url: "http://netbanking.apisec.ai:8080/v2/api-docs"
          email: "xxx@apisec.ai"
          sarif-result-file: "ethicalcheck-results.sarif"

       - name: Upload sarif file to repository
         uses: github/codeql-action/upload-sarif@v2
         with:
          sarif_file: ./ethicalcheck-results.sarif
name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  - name: "Check if user has write access"
    uses: "lannonbr/repo-permission-check-action@2.0.2"
    with:
      permission: "write"
    env:
      GITHUB_TOKEN: ${{github_pat
      - uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160
