- name: Maven Version Bump Action
  uses: nnichols/maven-version-bump-action@v4
- name : action/checkout
- uses : actions/checkout3
- name: Setup Java JDK
  uses: actions/setup-java@v3.9.0
[![Ruby on Rails CI](https://github.com/ah-ha-admin/refactored-memory/actions/workflows/rubyonrails.yml/badge.svg?event=workflow_dispatch)](https://github.com/ah-ha-admin/refactored-memory/actions/workflows/rubyonrails.yml)
main
- name: nodenv/setup-nodenv

  uses: nodenv/actions-setup-nodenv@v2.0.10
