 Run actions/deploy-pages@v1
 Actor:ah-ha-admin
 Action ID:3610059348
     Artifact URL:https://pipelines.actions.githubusercontent.com/4KXsrVU1mUOKs7pos5Bk6Fq09D6jySVjT3cpPMvrTyCLYNX7nf/_apis/pipelines/workflows/3610059348/artifacts?api-version=6.0-preview
      {"count":1,"value":[{"containerId":1385265,"size":102400,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/4KXsrVU1mUOKs7pos5Bk6Fq09D6jySVjT3cpPMvrTyCLYNX7nf/_apis/resources/Containers/1385265","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/4KXsrVU1mUOKs7pos5Bk6Fq09D6jySVjT3cpPMvrTyCLYNX7nf/_apis/pipelines/1/runs/1832/artifacts?artifactName=github-pages","expiresOn":"2022-12-04T20:12:07.8712362Z","items":null}]}
      Creating deployment with payload
{
	"artifact_url":"https://pipelines.actions.githubusercontent.com/4KXsrVU1mUOKs7pos5Bk6Fq09D6jySVjT3cpPMvrTyCLYNX7nf/_apis/pipelines/1/runs/1832/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version:"d844251c0b0442681cc87b49a1acb46f9109b099",
	"oidc_token":"***"
}
Created deployment for d844251c0b0442681cc87b49a1acb46f9109b099
{"page_url":"https://ah-ha-admin.github.io/refactored-memory/","status_url":"https://api.github.com/repos/ah-ha-admin/refactored-memory/pages/deployment/status/d844251c0b0442681cc87b49a1acb46f9109b099","preview_url":""}
Reported success!
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
- name:Maven Version Bump Action
  uses:nnichols/maven-version-bump-action@v4
- name :action/checkout
- uses :actions/checkout3
- name:Setup Java JDK
  uses:actions/setup-java@v3.9.0
- name:nodenv/setup-nodenv
  uses:nodenv/actions-setup-nodenv@v2.0.10
