[![Ruby on Rails CI](https://github.com/ah-ha-admin/refactored-memory/actions/workflows/rubyonrails.yml/badge.svg?event=workflow_dispatch)](https://github.com/ah-ha-admin/refactored-memory/actions/workflows/rubyonrails.yml)
