name: static analysis

on: [ push ]

jobs:
  static-analysis:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: cargo clippy --fix
      - run: cargo fmt

      - uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84
