# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Upgrade to the latest Python syntax with https://github.com/asottile/pyupgrade
      - uses: install-pinned/pyupgrade@2438dd5b51107d2bebff5e85c46a0849fdad0e95
      - name: Run pyupgrade
        run: |  
          shopt -s globstar
          pyupgrade --exit-zero-even-if-changed --py39-plus **/*.py

      # Sort imports with https://github.com/asottile/reorder_python_imports
      - uses: install-pinned/reorder_python_imports@0505c9cc1805564ca09905637e20d334990501a0
      - name: Run reorder-python-imports
        run: |
         shopt -s globstar
         reorder-python-imports --exit-zero-even-if-changed --py39-plus **/*.py

      # Remove unused imports with https://github.com/PyCQA/autoflake
      - uses: install-pinned/autoflake@32877f5112ce1c5b8b30cf57d70593a53d5fca87
      - run: autoflake --in-place --remove-all-unused-imports -r .

      # Format your code with https://github.com/psf/black
      - uses: install-pinned/black@dde5aed720bc458e86d99144d4d0c1f6c8e08844
      - run: black .

      - uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c016
