# -- stackhawk configuration for hawk.Pef2X0hP8ryJcWfE23Mt.g1vMt73kbxSNZrRdCazs --
app:
  # -- An applicationId obtained from the StackHawk platform. --
  applicationId: e621fda3-a65e-48bc-827b-7a8e1c1251f4 # (required)
  # -- The environment for the applicationId defined in the StackHawk platform. --
  env: Production # (required)
  # -- The url of your application to scan --
  host: https://ah-ha-admin.io/refactored-memory # (required)

# -- Customized Configuration for GraphQL/SOAP/OpenAPI, add here --
  # Configuration Docs: https://docs.stackhawk.com/hawkscan/configuration/

# -- If Authenticated Scanning is needed, add here --
  # Authenticated Scanning Docs: https://docs.stackhawk.com/hawkscan/authenticated-scanning.html
  # Authenticated Scanning Repo: https://github.com/kaakaww/scan-configuration/tree/main/Authentication

# -- Help Section --
  # Docs: https://docs.stackhawk.com/
  # Contact Support: support@stackhawk.com
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

#           🦅 STACKHAWK        https://stackhawk.com

# The StackHawk HawkScan action makes it easy to integrate dynamic application security testing (DAST) into your
# CI pipeline. See the Getting Started guide (https://docs.stackhawk.com/hawkscan/) to get up and running with
# StackHawk quickly.

# To use this workflow, you must:
#
# 1.  Create an API Key and Application: Sign up for a free StackHawk account to obtain an API Key and
#     create your first app and configuration file at https://app.stackhawk.com.
#
# 2.  Save your API Key as a Secret: Save your API key as a GitHub Secret named HAWK_API_KEY.
#
# 3.  Add your Config File: Add your stackhawk.yml configuration file to the base of your repository directory.
#
# 4.  Set the Scan Failure Threshold: Add the hawk.failureThreshold configuration option
#     (https://docs.stackhawk.com/hawkscan/configuration/#hawk) to your stackhawk.yml configuration file. If your scan
#     produces alerts that meet or exceed the hawk.failureThreshold alert level, the scan will return exit code 42
#     and trigger a Code Scanning alert with a link to your scan results.
#
# 5.  Update the "Start your service" Step: Update the "Start your service" step in the StackHawk workflow below to
#     start your service so that it can be scanned with the "Run HawkScan" step.


name: "StackHawk"

on:
  push:
    branches: [ "main", all ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '36 8 * * 4'

permissions:
  contents: read

jobs:
  stackhawk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for stackhawk/hawkscan-action to upload code scanning alert info
    name: StackHawk
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start your service
        run: ./your-service.sh &                  # ✏️ Update this to run your own service to be scanned

      - name: Run HawkScan
        uses: stackhapwk/hawkscan-action@22175e2df78e85b78a2741aedf20466aca829580
        continue-on-error: true                   # ✏️ Set to false to break your build on scan errors
        with:
         apiKey: ${{hawk.Pef2X0hP8ryJcWfE23Mt.g1vMt73kbxSNZrRdCazs}}
          codeScanningAlerts: true
          githubToken: ${{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}}
          jobs:
  stackhawk-hawkscan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stackhawk/hawkscan-action@v2.0.1
      with:
        apiKey: ${{hawk.Pef2X0hP8ryJcWfE23Mt.g1vMt73kbxSNZrRdCazs}}
        configurationFiles: stackhawk.yml stackhawk-extra.yml
          docker run --rm -v $(pwd):/hawk:rw -it stackhawk/hawkscan
# -- stackhawk configuration for hawk.Pef2X0hP8ryJcWfE23Mt.g1vMt73kbxSNZrRdCazs --
app:
  # -- An applicationId obtained from the StackHawk platform. --
  applicationId: e621fda3-a65e-48bc-827b-7a8e1c1251f4 # (required)
  # -- The environment for the applicationId defined in the StackHawk platform. --
  env: Production # (required)
  # -- The url of your application to scan --
  host: https://ah-ha-admin.io/refactored-memory # (required)


# -- Customized Configuration for GraphQL/SOAP/OpenAPI, add here --
  # Configuration Docs: https://docs.stackhawk.com/hawkscan/configuration/

# -- If Authenticated Scanning is needed, add here --
  # Authenticated Scanning Docs: https://docs.stackhawk.com/hawkscan/authenticated-scanning.html
  # Authenticated Scanning Repo: https://github.com/kaakaww/scan-configuration/tree/main/Authentication

# -- Help Section --
  # Docs: https://docs.stackhawk.com/
  # Contact Support: support@stackhawk.com
app:
  applicationId: e621fda3-a65e-48bc-827b-7a8e1c1251f4
  host: https://localhost:3001
  env: Production

hawk:
  startupTimeoutMinutes: 1
  spider:
    base: false
