name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{latest}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{latest}}
    - name: Build
      run: |
        npm install
        npx webpack
